### ISSUE TITLE
last suite is duplicated if packages are used

### ISSUE THREAD

**Issue by oskliarov** [allure-framework/allure-nose#6]
### steps

create python packages structure like 

```
root
    __init__.py
    tests
           __init__.py
           test.py
```

wiht test.py like this

``` python
import nose

def test():
    with nose.allure.step("Step"):
        assert True
```

after test run, **two** xml with similar content are created.
### suggestion

It looks like a problem is in this place of nose plugin

``` python
    def stopContext(self, context):
        if isinstance(context, ModuleType):
            self.allure.impl.stop_suite()
```

`stop_suite` is called for each module in hierarchy.

I think the following code should manage this problem

``` python
    def stopContext(self, context):
        if isinstance(context, ModuleType) and self.allure.impl.testsuite is not None:
            self.allure.impl.stop_suite()
            self.allure.impl.testsuite = None
```

**Comment by sergeychipiga** [comment]
@oskliarov thank you for your report! It will be fixed this week

**Comment by F1ashhimself** [comment]
@oskliarov could you please verify that this was fixed by pull request #8

**Comment by mkulava** [comment]
@F1ashhimself this issue is still reproduced in version 1.0.5
